# Generated by Django 2.2.2 on 2019-06-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Article',
        ),
    ]
